### ISSUE TITLE
Instabilidade no modelo do robô genérico

### ISSUE THREAD

**Issue by lucastrschneider** [ThundeRatz/travesim#21]
Não sei exatamente se isso é um bug mesmo, mas só pra deixar aqui, eu fui testar algumas coisinhas usando o rqt_steering_topic, e percebi que tem uns omportamentos estranhos as vezes.

A primeira coisa foi esse balanço quando eu colocava só uma velocidade angular.

![angular_bug](https://user-images.githubusercontent.com/50970346/112880069-5c249300-90a0-11eb-8b8e-cb7adb381c5a.gif)

Ele fica balançando pra frente e pra tras, e fica travando as vezes.

Outra coisa que aconteceu bastante foi dele ficar bastante descontrolado e não consegui seguir nem de perto uma linha reta quando eu colocava uma velocidade linear.

![linear_bug_1](https://user-images.githubusercontent.com/50970346/112880213-88401400-90a0-11eb-9f0a-4ced1019613a.gif)

![linear_bug_2](https://user-images.githubusercontent.com/50970346/112880227-8d04c800-90a0-11eb-9609-a2077ecdbe26.gif)

Não sei, pra mim parece que é um problema no modelo que ta causando esses comportamentos, mas posso estar errado. Vocês perceberam algo assim também? Aqui acontece quase sempre algo do tipo.

O mais estranho é que não lembro desse tipo de coisa acontecer tão frequentemente quando a gente usava o nosso modelo mesmo, por isso acredito que esse seja o problema, mas não tenho certeza.

**Comment by FelipeGdM** [comment]
Salve salve amantes do mundo da bola

Filosoficamente falando, eu não caracterizaria nenhum dos dois comportamentos como bug. Se você parar pra analisar a física envolvida, os dois comportamentos são coerentes

A começar:

> A primeira coisa foi esse balanço quando eu colocava só uma velocidade angular.

Quando o robô gira com velocidade angular constante, a única posição de equilíbrio seria com o robô perfeitamente de pé, uma vez que o robô é perfeitamente simétrico e o centro de massa se encontra exatamente no eixo médio do robô. No entanto, é importante notar que essa posição de equilíbrio é uma posição de equilíbrio instável, de modo que o robô não converge pra nenhuma posição preferencial

Em segundo

> Outra coisa que aconteceu bastante foi dele ficar bastante descontrolado e não consegui seguir nem de perto uma linha reta quando eu colocava uma velocidade linear.

"Descontrolado" eu achei que você pegou pesado hahahaha. Pelo gif que você mostrou aí, tenho um bom palpite de qual pode ser a causa desse problema. Acredito que no momento em que o robô acelera, temos derrapamento das rodas, de modo que o robô acaba girando ao invés de ir reto. No momento em que a aceleração do robô diminui, as rodas param de deslizar e o robô volta a andar em linha reta, da forma que acontece no seu gif.

Para explicar direitinho, vou fazer uso do diagrama de corpo livre do robô

![image](https://user-images.githubusercontent.com/1054087/112920520-8184c180-90df-11eb-965d-34fe25776f93.png)

Supondo que a roda do robô não derrapa, temos que

![image](https://user-images.githubusercontent.com/1054087/112920818-17b8e780-90e0-11eb-8791-aa5127fa1299.png)

Se o roda derrapa, a segunda equação deixa de valer e não podemos mais calcular a aceleração do robô em função do torque do motor. Agora, como calcular o valor da força de atrito?

![image](https://user-images.githubusercontent.com/1054087/112920971-5c448300-90e0-11eb-92d9-d2e2c34a3bd7.png)

A força máxima de atrito é proporcional à normal da roda com o chão. Se o robô acelera para a esquerda (essa imagem está invertida em relação às outras, vacilei >.<), a força normal do robô é dividida entre o ponto de contato da roda e do corpo do robô. Dessa forma, quanto maior a aceleração do robô, menor a normal no ponto de contato e portanto menor a força máximo de atrito.

Deu pra pegar a ideia?

Sobre isso

> O mais estranho é que não lembro desse tipo de coisa acontecer tão frequentemente quando a gente usava o nosso modelo mesmo, por isso acredito que esse seja o problema, mas não tenho certeza.

Sobre o primeiro problema, o nosso robô era assimétrico, né? Não temos o mesmo padrão de equilíbrio instável pois o centro de massa do robô não está mais no eixo médio do robô

Sobre o segundo problema, nós mudamos completamente a relação de torque-velocidade no novo modelo, de modo que é esperado que o comportamento seja diferente.

Em todo caso, quando estiver desconfiado do comportamento físico da simulação, minha sugestão é diminuir o *max step size*, de modo que o Gazebo dê passos menores no tempo e diminua o erro de aproximação numérica (é importante não diminuir indefinidamente, pois esbarramos num aumento da complexidade da simulação e do erro de truncamento). Pra simulação não ficar mais lenta, você pode aumentar o *real time update rate* de acordo com a variação do max step size. A simulação ficará mais pesada, mas a velocidade dela permanecerá a mesma.

No mais, confesso que fico curioso de saber como o FiraSim performa nas mesmas condições que você descreveu aqui

Fiquem bem e mantenham-se hidratados
